### ISSUE TITLE
PrivateKey in config does not match id

### ISSUE THREAD

**Issue by agmap** [SgtPooki/npm-bulk-import-cid#7]
See:
![image](https://github.com/user-attachments/assets/09b06a55-3af5-48cd-9d32-42e75f2818b9)

**Comment by SgtPooki** [comment]
This may be because you have two running nodes at the same time? did you make sure no other ipfs node was running when you ran the bulk-import-cid command?

**Comment by agmap** [comment]
Thank you for your help.
It must be a Windows issue. I have already tried using admin rights, configuring Windows environment variables for ipfs ...  All to no success. It does not seem to be using the ipfs-desktop configuration.  /.ipfs
No other ipfs node is running.

**Comment by agmap** [comment]
Now its working.
IIt seems I can not `Move Repository Location` in ipfs-desktop.
